ShoesShopOnline/Models/SanPham.cs
namespace ShoesShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("SanPham")]
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            AnhMoTas = new HashSet<AnhMoTa>();
        }

        [Key]
        [StringLength(10)]
        [DisplayName("Mã sản phẩm")]
        [Required(ErrorMessage = "Mã sản phẩm không được để trống !")]
        public string MaSP { get; set; }

        [StringLength(200)]
        [DisplayName("Tên sản phẩm")]
        [Required(ErrorMessage = "Tên sản phẩm không được để trống !")]
        public string TenSP { get; set; }

        [StringLength(20)]
        [DisplayName("Mã danh mục")]
        [Required(ErrorMessage = "Mã danh mục không được để trống !")]
        public string MaDM { get; set; }

        [StringLength(500)]
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Mô tả không được để trống !")]
        public string MoTa { get; set; }

        [Column(TypeName = "money")]
        [DisplayName("Giá bán")]
        [Required(ErrorMessage = "Giá bán không được để trống !")]
        public decimal GiaBan { get; set; }

        public DateTime NgayTao { get; set; }

        public DateTime NgaySua { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhMoTa> AnhMoTas { get; set; }

        public virtual DanhMucSP DanhMucSP { get; set; }
    }
}

ShoesShopOnline/Areas/Admin/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using ShoesShopOnline.Models;

namespace ShoesShopOnline.Areas.Admin.Controllers
{
    public class SanPhamsController : BaseController
    {
        private Shoes db = new Shoes();

        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            var result = db.SanPhams.Join(db.AnhMoTas, p => p.MaSP, a => a.MaSP, (p, a) => new ProductDetail
            {
                MaSP = p.MaSP,
                TenSP = p.TenSP,
                MaDM = p.DanhMucSP.TenDanhMuc,
                Anh = a.HinhAnh,
                MoTa = p.MoTa,
                GiaBan = p.GiaBan,
                NgaySua = p.NgaySua,

            }).ToList();
            var productDetails = new List<ProductDetail>();
            foreach (var item in result)
            {
                int dem = 0;
                foreach (var t in productDetails)
                {
                    if (item.MaSP.Equals(t.MaSP))
                        dem++;
                }
                if (dem == 0)
                    productDetails.Add(item);
            }
            productDetails = productDetails.OrderByDescending(p => p.NgaySua).ToList();
            ViewBag.CurrentSort = sortOrder;
            ViewBag.SapTheoTen = String.IsNullOrEmpty(sortOrder) ? "ten_desc" : "";
            ViewBag.SapTheoGia = sortOrder == "gia" ? "gia_desc" : "gia";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                productDetails = productDetails.Where(p => p.TenSP.ToLower().Contains(searchString.ToLower())).ToList();
            }
            switch (sortOrder)
            {
                case "ten_desc":
                    productDetails = productDetails.OrderByDescending(p => p.TenSP).ToList();
                    break;
                case "gia":
                    productDetails = productDetails.OrderBy(p => p.GiaBan).ToList();
                    break;
                case "gia_desc":
                    productDetails = productDetails.OrderByDescending(p => p.GiaBan).ToList();
                    break;
                default:
                    productDetails = productDetails.OrderByDescending(p => p.NgaySua).ToList();
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(productDetails.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Details(string id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                SanPham sanPham = db.SanPhams.Find(id);
                if (sanPham == null)
                {
                    return HttpNotFound();
                }
                var images = db.AnhMoTas.Where(p => p.MaSP == id).ToList();
                var maAnh = 0;
                string filePath = "";
                if (images != null)
                {
                    foreach (var item in images)
                    {
                        filePath += item.HinhAnh + ";";
                        maAnh = item.MaAnh;
                    }
                }
                filePath = filePath.Substring(0, filePath.Length - 1);
                ViewBag.filePath = filePath;
                var sizes = db.ChiTietSanPhams.Where(p => p.MaAnh == maAnh).ToList();
                string listSize = "";
                if (sizes != null)
                {
                    foreach (var item in sizes)
                    {
                        listSize += item.KichCo + "; ";
                    }
                }
                listSize = listSize.Substring(0, listSize.Length - 2);
                ViewBag.listSize = listSize;
                return View(sanPham);
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi !" + ex.Message;
                return View();
            }

        }

        public ActionResult Create()
        {
            ViewBag.MaDM = new SelectList(db.DanhMucSPs, "MaDM", "TenDanhMuc");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductDetail productDetail, List<HttpPostedFileBase> uploadFile)
        {
            try
            {
                productDetail.Anh = "";
                if (ModelState.IsValid)
                {
                    SanPham sanPham = new SanPham();
                    string maSP = "";
                    var list = db.SanPhams.ToList();
                    var sanpham = list.LastOrDefault();
                    if (sanpham == null)
                    {
                        maSP = "SP001";
                    }
                    else
                    {
                        int index = int.Parse(sanpham.MaSP.Substring(2, 3)) + 1;
                        maSP = "SP" + string.Format(CultureInfo.CreateSpecificCulture("da-DK"), "{0:000}", index);
                    }
                    sanPham.MaSP = maSP;
                    sanPham.TenSP = productDetail.TenSP;
                    sanPham.MaDM = productDetail.MaDM;
                    sanPham.MoTa = productDetail.MoTa;
                    sanPham.GiaBan = productDetail.GiaBan;
                    sanPham.NgayTao = DateTime.Now;
                    sanPham.NgaySua = DateTime.Now;
                    db.SanPhams.Add(sanPham);
                    db.SaveChanges();
                    //Add Anh
                    string[] sizes = productDetail.Size.Split(';');
                    foreach (var item in uploadFile)
                    {
                        AnhMoTa anhMoTa = new AnhMoTa();
                        string FileName = item.FileName;
                        string filePath = Path.Combine(HttpContext.Server.MapPath("/wwwroot/Images"),
                                                       Path.GetFileName(item.FileName));
                        item.SaveAs(filePath);
                        anhMoTa.HinhAnh = FileName;
                        anhMoTa.MaSP = maSP;
                        db.AnhMoTas.Add(anhMoTa);
                        db.SaveChanges();
                        //Add san pham chi tiet
                        for (int j = 0; j < sizes.Length; j++)
                        {
                            ChiTietSanPham chiTietSanPham = new ChiTietSanPham();
                            chiTietSanPham.MaAnh = anhMoTa.MaAnh;
                            chiTietSanPham.KichCo = int.Parse(sizes[j]);
                            db.ChiTietSanPhams.Add(chiTietSanPham);
                            db.SaveChanges();
                        }
                    }

                    return RedirectToAction("Index");
                }
                ViewBag.MaDM = new SelectList(db.DanhMucSPs, "MaDM", "TenDanhMuc", productDetail.MaDM);
                return View(productDetail);
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu !" + ex.Message;
                ViewBag.MaDM = new SelectList(db.DanhMucSPs, "MaDM", "TenDanhMuc", productDetail.MaDM);
                return View(productDetail);

            }

        }

        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            int maAnh = 0;
            var images = db.AnhMoTas.Where(p => p.MaSP == id).ToList();
            string filePath = "";
            if (images != null)
            {
                foreach (var item in images)
                {
                    maAnh = item.MaAnh;
                    filePath += item.HinhAnh + ";";
                }
            }
            filePath = filePath.Substring(0, filePath.Length - 1);
            ViewBag.filePath = filePath;
            string listSize = "";
            var sizes = db.ChiTietSanPhams.Where(p => p.MaAnh == maAnh).ToList();
            if (sizes != null)
            {
                foreach (var item in sizes)
                {
                    listSize += item.KichCo + ";";
                }
            }
            listSize = listSize.Substring(0, listSize.Length - 1);
            ViewBag.listSize = listSize;
            ViewBag.MaDM = new SelectList(db.DanhMucSPs, "MaDM", "TenDanhMuc", sanPham.MaDM);
            ProductDetail productDetail = new ProductDetail()
            {
                MaSP = sanPham.MaSP,
                TenSP = sanPham.TenSP,
                GiaBan = sanPham.GiaBan,
                Anh = filePath,
                Size = listSize,
                MoTa = sanPham.MoTa,
                MaDM = sanPham.MaDM,
                NgayTao = sanPham.NgayTao,
                NgaySua = sanPham.NgaySua,
                DanhMucSP = sanPham.DanhMucSP
            };
            return View(productDetail);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductDetail productDetail, List<HttpPostedFileBase> uploadFile, string id)
        {
            try
            {
                if (productDetail.Anh == null && uploadFile == null)
                {

ShoesShopOnline/Areas/Admin/Views/SanPhams/Create.cshtml
@model ShoesShopOnline.Models.ProductDetail

@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <style>
        .row {
            width: 25%;
            float: left;
            padding: 10px 20px;
        }

        a[class="btnAddNew"] {
            color: white;
            background-color: navy;
            padding: 10px;
            border: none;
            width: 100px;
            border-radius: 5px;
            text-align: center;
            margin-top: 20px;
            height: 50px;
            line-height: 50px;
        }

        a[class="btnRemove"] {
            height: 30px;
            line-height: 30px;
            color: white;
            background-color: red;          
            border: none;
            width: 60px;
            border-radius: 5px;
            margin: 15px 10px;
            text-align: center;
        }

        img {
            padding: 10px 20px;
        }
    </style>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var max_fields = 10; //maximum input boxes allowed
            var wrapper = $(".myinput"); //Fields wrapper
            var add_button = $(".btnAddNew"); //Add button ID

            var x = 0; //initlal text box count
            $(add_button).click(function (e) { //on add input button click
                e.preventDefault();
                if (x < max_fields) { //max input box allowed
                    x++; //text box increment
                    $(wrapper).append('<div class="row"> <img class="img-rounded output" alt="Ảnh" width="100" height="230" src="~/wwwroot/Images/h0.png" />  <input type="file" name="uploadFile[' + x + ']" onchange="loadFile(event)"/><a href="#" class="btnRemove">Xóa</a></div>'); //add input box

                }
            });

            $(wrapper).on("click", ".btnRemove", function (e) { //user click on remove text
                e.preventDefault(); $(this).parent('div').remove(); x--;
            })
        });
    </script>
    @section Ckeditor{
        <script>
            CKEDITOR.replace("MoTa");
        </script>
    }
</head>
<body>
    @if (ViewBag.Error != null)
    {
        <br />
        <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
    }
@using (Html.BeginForm("Create", "SanPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Thêm sản phẩm mới</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaDM, "MaDM", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaDM", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class=" form-group">
        <label>Ảnh sản phẩm </label><br />
        <a class="btnAddNew ThemMoi" href="#">Thêm Ảnh</a>
        <br />
        <div id="myinput" class="myinput">
            <div class="row">
                <img class="img-rounded output" alt="Ảnh" width="100" height="230" src="~/wwwroot/Images/h0.png" />
                <input type="file" name="uploadFile[0]" required onchange="loadFile(event)" /><br />
            </div>
        </div>
        <br />
    </div>
    <div class="form-group" style="clear:both">
        @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control", rows = 50 } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <hr />
            <input class="btn ThemMoi" style="margin-right:20px"type="submit" value="Thêm" />
            <a class="btn ThemMoi" href="~/Admin/SanPhams/Index">Hủy</a>
        </div>
    </div>
</div>
}

    <script>
        var loadFile = function (event) {
            var images = document.getElementsByClassName('output');
            var image = images[images.length - 1];
            image.src = URL.createObjectURL(event.target.files[0]);

        }
    </script>

</body>
</html>

ShoesShopOnline/Areas/Admin/Views/SanPhams/Details.cshtml
@model ShoesShopOnline.Models.SanPham

@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
    string[] images = ViewBag.filePath.Split(';');
    string image = "";
    for (int i = 0; i < images.Length; i++)
    {
        image += "<img class=\"rounded\" alt=\"Ảnh\" style=\"margin: 20px\" width=\"150\" height=\"150\" src=\"/wwwroot/Images/" + images[i] + "\">";
    }
}

    <div>
        <h4>@Model.TenSP</h4>
        <hr />
        <div>
            <label for="TenDM">Danh mục :</label>
            <span>@Model.DanhMucSP.TenDanhMuc</span>
        </div>
        <div>
            @Html.Raw(System.Web.HttpUtility.HtmlDecode(image))
        </div>
        <div>
            <label for="MoTa">Mô tả :</label>
            @Html.Raw(System.Web.HttpUtility.HtmlDecode(@Model.MoTa))
        </div>
        <div>
            <label for="GiaBan">Giá bán :</label>
            <span>@string.Format(info, "{0:c0}", Model.GiaBan)</span>
        </div>
        <div>
            <label for="GiaBan">Các size sẵn có :</label>
            <span>@ViewBag.listSize</span>
        </div>
        <div>
            <label for="NgayTao">Ngày tạo :</label>
            <span>@Model.NgayTao</span>
        </div>
        <div>
            <label for="NgaySua">Ngày sửa :</label>
            <span>@Model.NgaySua</span>
        </div>
    </div>
    <p>
        <hr />
        <a class="btn ThemMoi" style="margin-right:20px" href="~/Admin/SanPhams/Edit/@Model.MaSP">Sửa sản phẩm</a>
        <a class="btn ThemMoi" href="~/Admin/SanPhams/Index">Trở về</a>
    </p>

ShoesShopOnline/Areas/Admin/Views/SanPhams/Edit.cshtml
@model ShoesShopOnline.Models.ProductDetail

@{
    string name = ViewBag.filePath;
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    string image = "";
    if (ViewBag.filePath != null) {
        string[] images = ViewBag.filePath.Split(';');
        for (int i = 0; i < images.Length; i++)
        {
            image += "<div class=\"row\"><img class=\"img-rounded output\" name=\"uploadFile[" + i + "]\" alt=\"Ảnh\" width=\"100\" height=\"230\" src=\"/wwwroot/Images/" + images[i] + "\"><br/><a href=\"#\" class=\"btnRemove\">Xóa</a></div>";
        }
    }
    
    else
    {
        image = "";
    }

}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <style>
        .row {
            width: 25%;
            float: left;
            padding: 10px 20px;
        }

        a[class="btnAddNew"] {
            color: white;
            background-color: navy;
            padding: 10px;
            border: none;
            width: 300px;
            border-radius: 5px;
            text-align: center;
            margin-top: 20px;
            height: 50px;
            line-height: 50px;
        }

        a[class="btnRemove"] {
            height: 30px;
            line-height: 30px;
            color: white;
            background-color: red;
            border: none;
            width: 60px;
            border-radius: 5px;
            margin: 15px 10px;
            text-align: center;
        }

        a[class="btnRemoveNew"] {
            height: 30px;
            line-height: 30px;
            color: white;
            background-color: red;
            border: none;
            width: 60px;
            border-radius: 5px;
            margin: 15px 10px;
            text-align: center;
        }

        img {
            padding: 10px 20px;
        }
    </style>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var max_fields = 10; //maximum input boxes allowed
            var wrapper = $(".myinput"); //Fields wrapper
            var add_button = $(".btnAddNew"); //Add button ID


            var t = 0;
            var indexmoi = 0;
            var indexcu = 100;
            var x = 0; //initlal text box count
            $(add_button).click(function (e) { //on add input button click
                e.preventDefault();
                if (x < max_fields) { //max input box allowed
                    x++; //text box increment
                    $(wrapper).append('<div class="row"> <img class="img-rounded output" alt="Ảnh" width="100" height="230" src="~/wwwroot/Images/h0.png" />  <input type="file" name="uploadFile" onchange="loadFile(event)"/><a href="#" class="btnRemoveNew">Xóa</a></div>'); //add input box

                }
            });

            $(wrapper).on("click", ".btnRemove", function (e) { //user click on remove text
                value = $(this).parent().parent().prev().children(':first-child').val();
                if (value != "") {
                    name = $(this).prev().prev().attr("name");
                    indexmoi = name.match(/[0-9]+/)[0];
                    if (indexmoi > indexcu) {
                        t++;
                        indexmoi = indexmoi - t;
                    }
                    indexcu = indexmoi;


                    var list = value.split(';');
                    list.splice(indexmoi, 1);
                    var result = "";
                    for (let i = 0; i < list.length; i++) {
                        result += list[i] + ";";
                    }
                    result = result.substring(0, result.length - 1);
                    $(this).parent().parent().prev().children(':first-child').val(result);
                }

                e.preventDefault(); $(this).parent('div').remove(); x--;

            })
            //Remove Image New
            $(wrapper).on("click", ".btnRemoveNew", function (e) { //user click on remove text
                e.preventDefault(); $(this).parent('div').remove(); x--;
            })
        });
    </script>
    @section Ckeditor{
        <script>
            CKEDITOR.replace("MoTa");
        </script>
    }
</head>
<body>
    @if (ViewBag.Error != null)
    {
        <br />
        <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
    }
    @using (Html.BeginForm("Edit", "SanPhams", FormMethod.Post, new { enctype = "multipart/form-data", MaSP=Model.MaSP }))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Cập nhật thông tin sản phẩm</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaDM, "MaDM", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaDM", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class=" form-group">
        <label>Ảnh sản phẩm </label><br />
        <a class="btnAddNew ThemMoi" href="#">Thêm Ảnh</a>
        <br />
        <div class="col-md-10">
            @Html.EditorFor(model => model.Anh, new { htmlAttributes = new { @class = "form-control", style = "visibility:hidden;" } })
            @Html.ValidationMessageFor(model => model.Anh, "", new { @class = "text-danger" })
        </div>
        <div id="myinput" class="myinput">
            @Html.Raw(System.Web.HttpUtility.HtmlDecode(image))
        </div>
        <br />
    </div>
    <div class="form-group" style="clear:both">
        @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control", rows = 50 } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <hr />
            <input class="btn ThemMoi" style="margin-right:20px" type="submit" value="Lưu" />
            <a class="btn ThemMoi" href="~/Admin/SanPhams/Index">Hủy</a>
        </div>
    </div>
</div>
    }

    <script>
        var loadFile = function (event) {
            var images = document.getElementsByClassName('output');
            var image = images[images.length - 1];
            image.src = URL.createObjectURL(event.target.files[0]);
        }
    </script>

</body>
</html>

ShoesShopOnline/Areas/Admin/Views/SanPhams/Index.cshtml
@model PagedList.IPagedList<ShoesShopOnline.Models.ProductDetail>
@using PagedList.Mvc
<link href="~/Content/PagedList.css" rel="stylesheet" />
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
}

@section script{
    <script src="~/Areas/Admin/Assets/JS/SanPham.js"></script>
}
<head>
    <style>
       button a {
            color: white;
        }

       button a:hover {
            color: yellow;
       }
        /* .tim{
           background-color:black;
           color:white;
       }*/ 
    </style>
</head>
<h2>Danh sách sản phẩm</h2>
@using (Html.BeginForm())
{
    <p>
        <button style="background-color: #428BCA; border-radius: 8px; border: none; margin: 10px 0px; padding: 7px 9px;">@Html.ActionLink("Thêm mới", "Create")</button>
    <div style="float:right;">
        Tìm sản phẩm: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
   <input class="tim" type="submit" value="Tìm" />
    </div>
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Tên sản phẩm", "Index", new { sortOrder = ViewBag.SapTheoTen, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Ảnh
        </th>
        <th>
            @Html.ActionLink("Giá bán", "Index", new { sortOrder = ViewBag.SapTheoGia, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Danh mục
        </th>
        <th>
            Ngày cập nhật
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr id="row-@item.MaSP">
            <td style="width:20%">
                @Html.DisplayFor(modelItem => item.TenSP)
            </td>
            <td>
                @{
                    string ImagePath = "~/wwwroot/Images/" + item.Anh;
                }
                <img src="@Url.Content(ImagePath)" width="100" class="img-thumbnail" />
            </td>
            <td>
                @string.Format(info, "{0:c0}", item.GiaBan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaDM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgaySua)
            </td>
            <td>
                <a class="ThemMoi" href="~/Admin/SanPhams/Edit/@item.MaSP"  style="background:#DAA520;color:#fff;border:none">Sửa</a>|
                <a class="ThemMoi" href="~/Admin/SanPhams/Details/@item.MaSP" style="  background: #2f4f4f;color:#FFF;border:none">Chi tiết</a>|
                <a class=" btnDelete ThemMoi" dataname="@item.MaSP" style="background: #FF6347;color:#fff;border:none">Xóa</a>
            </td>
            
        </tr>
    }

</table>
    Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new
    {
        page,
        sortOrder = ViewBag.CurrentSort,
    currentFilter = ViewBag.CurrentFilter
    }))