ShoesShopOnline/Controllers/AccountUserController.cs
using ShoesShopOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoesShopOnline.Controllers
{
    public class AccountUserController : Controller
    {
        Shoes db = new Shoes();
        // GET: AccountUser
        [HttpGet]
        public ActionResult ChangePassWord()
        {
            if (Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION] == null || Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION].ToString() == "")
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassWord(string oldpassword, string password)
        {
            TaiKhoanNguoiDung tk = (TaiKhoanNguoiDung)Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION];
            if (tk.MatKhau != oldpassword)
            {
                ModelState.AddModelError("ErrorUpdate", "Mật khẩu cũ không đúng");
            }
            else
            {
                TaiKhoanNguoiDung edit = db.TaiKhoanNguoiDungs.Where(a => a.MaTK.Equals(tk.MaTK)).FirstOrDefault();
                edit.MatKhau = password;
                db.SaveChanges();
                Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION] = edit;
                ModelState.AddModelError("ErrorUpdate", "Đổi mật khẩu thành công!");
            }
            return View();
        }


        [HttpGet]
        public ActionResult UserInfor(int id)
        {
            TaiKhoanNguoiDung session = (TaiKhoanNguoiDung)Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION];
            if (session == null)
            {
                return RedirectToAction("PageNotFound", "Error");
            }
            else
            {
                TaiKhoanNguoiDung tk = db.TaiKhoanNguoiDungs.Where(a => a.MaTK.Equals(id)).FirstOrDefault();
                return View(tk);
            }
        }

        [HttpPost]
        public ActionResult UserInfor([Bind(Include = "MaTK,HoTen,SDT,DiaChi,Email")] TaiKhoanNguoiDung tk)
        {
            TaiKhoanNguoiDung edit = db.TaiKhoanNguoiDungs.Where(a => a.MaTK.Equals(tk.MaTK)).FirstOrDefault();
            try
            {
                edit.HoTen = tk.HoTen;
                edit.DiaChi = tk.DiaChi;
                edit.Email = tk.Email;
                edit.SDT = tk.SDT;
                db.SaveChanges();
                Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION] = edit;
            }
            catch (Exception)
            {
                ModelState.AddModelError("ErrorUpdate", "Cập nhật thông tin không thành công ! Thử lại sau !");
            }
            return View(edit);
        }
    }
}

ShoesShopOnline/Controllers/BillController.cs
using PagedList;
using ShoesShopOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ShoesShopOnline.Controllers
{
    public class BillController : Controller
    {
        Shoes db = new Shoes();

        // GET: Bill
        [HttpGet]
        public ActionResult Index(int? page)
        {
            if (Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION] == null || Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION].ToString() == "")
            {
                return RedirectToAction("Login", "Home");
            }
            List<HoaDon> list = new List<HoaDon>();
            TaiKhoanNguoiDung tk = (TaiKhoanNguoiDung)Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION];
            list = db.HoaDons.Where(p => p.MaTK == tk.MaTK).OrderByDescending(x => x.NgayLap).ToList();
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            TaiKhoanNguoiDung tk = (TaiKhoanNguoiDung)Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION];
            if (tk == null)
            {
                return RedirectToAction("PageNotFound", "Error");
            }
            else
            {
                if (db.HoaDons.FirstOrDefault(x => x.MaTK == tk.MaTK) == null)
                {
                    return RedirectToAction("PageNotFound", "Error");
                }
            }
            var hoadons = db.ChiTietHoaDons.Where(x => x.MaHD == id).ToList();
            var sanphams = new List<CartItem>();
            foreach (var item in hoadons)
            {
                var sanpham = new CartItem();
                sanpham.ChiTietSanPham = item.ChiTietSanPham;
                sanpham.Gia = item.ChiTietSanPham.AnhMoTa.SanPham.GiaBan;
                sanpham.MaAnh = item.MaAnh;
                sanpham.SoLuong = item.SoluongMua;
                sanpham.KichCo = item.KichCo;
                sanphams.Add(sanpham);
            }
            var hoadon = db.HoaDons.Where(x => x.MaHD == id).FirstOrDefault();
            ViewBag.HoaDon = hoadon;
            return View(sanphams);
        }


        [HttpPost]
        public ActionResult Details(int id, FormCollection collection)
        {

            TaiKhoanNguoiDung tk = (TaiKhoanNguoiDung)Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION];
            var hoaDon = db.HoaDons.Where(x => x.MaHD == id).FirstOrDefault();
            hoaDon.MaTK = tk.MaTK;
            hoaDon.HoTenNguoiNhan = collection["name"];
            hoaDon.SDTNguoiNhan = collection["phone"];
            hoaDon.EmailNguoiNhan = collection["email"];
            hoaDon.DiaChiNhan = collection["address"];
            hoaDon.GhiChu = collection["note"];
            db.SaveChanges();
            var hoadons = db.ChiTietHoaDons.Where(x => x.MaHD == id).ToList();
            var sanphams = new List<CartItem>();
            foreach (var item in hoadons)
            {
                var sanpham = new CartItem();
                sanpham.ChiTietSanPham = item.ChiTietSanPham;
                sanpham.Gia = item.ChiTietSanPham.AnhMoTa.SanPham.GiaBan;
                sanpham.MaAnh = item.MaAnh;
                sanpham.SoLuong = item.SoluongMua;
                sanpham.KichCo = item.KichCo;
                sanphams.Add(sanpham);
            }
            var hoadon = db.HoaDons.Where(x => x.MaHD == id).FirstOrDefault();
            ViewBag.HoaDon = hoadon;
            return View(sanphams);
        }
        [HttpPost]
        public JsonResult ChangeStatus(int mahd, string stt)
        {
            try
            {
                TaiKhoanNguoiDung tk = (TaiKhoanNguoiDung)Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION];
                HoaDon hd = db.HoaDons.Where(x => x.MaHD == mahd).FirstOrDefault();
                if (hd.TrangThai == "Đã thanh toán" || hd.TrangThai == "Đang giao hàng")
                {
                    return Json(new { status = false }, JsonRequestBehavior.AllowGet);
                }
                hd.TrangThai = stt;
                db.SaveChanges();
                return Json(new { status = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { status = false }, JsonRequestBehavior.AllowGet);
            }
        }



    }
}

ShoesShopOnline/Controllers/NewFeedController.cs
using ShoesShopOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoesShopOnline.Controllers
{
    public class NewFeedController : Controller
    {
        // GET: NewFeed
        Shoes db = new Shoes();
        public ActionResult Index()
        {
            var list = (from tt in db.TinTucs select tt);
            ICollection<TinTuc> news = (from tt in db.TinTucs orderby tt.NgayDang select tt).ToList();
            TinTuc newsfisrt = (from tt in db.TinTucs orderby tt.NgayDang select tt).FirstOrDefault();
            ViewBag.news = news;
            return View(newsfisrt);
        }
        public ActionResult Single(int ma)
        {
            var newfeed = (from tt in db.TinTucs where tt.MaTin.Equals(ma) select tt).FirstOrDefault();
            return View(newfeed);
        }
    }
}

ShoesShopOnline/Views/Shared/HeaderCart.cshtml
@model List<ShoesShopOnline.Models.CartItem>
@{ var sumItem = 0;
                foreach (var item in Model)
                {
                    sumItem += item.SoLuong;
                } }

<div class="cart box_1" style="margin-top:0px">
    <a href="/gio-hang" >
        <h3 style="margin-top:7px">
            <img src="~/Assets/Client/images/cart.png" alt="" />

            <span>
                <sup id="cartcount" count="@sumItem" style="background:red; padding:6px 9px; border-radius:50%">@sumItem</sup>
            </span>

        </h3>
    </a>
</div>

ShoesShopOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ShoesShopOnline/Views/Shared/_LayoutClient.cshtml
@{
    ShoesShopOnline.Models.TaiKhoanNguoiDung tk =
            (ShoesShopOnline.Models.TaiKhoanNguoiDung)HttpContext.Current.Session[ShoesShopOnline.Session.ConstaintUser.USER_SESSION];
}

<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>

<head>
    <title>XShop - Hệ thống bán giày thể thao số 1 tại Hà Nội</title>
    <link rel="icon" type="image/x-icon" href="~/wwwroot/Images/images.png">
    <link href="~/Assets/Client/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->


    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>
    <script src="~/Assets/Client/js/jquery.min.js"></script>
    <!-- Custom Theme files -->
    <!--theme-style-->
    <link href="~/Assets/Client/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="New Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--fonts-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />


    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
    <!--//fonts-->
    <!-- start menu -->
    <link href="~/Assets/Client/css/memenu.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="~/Assets/Client/js/memenu.js"></script>
    <script>$(document).ready(function () { $(".memenu").memenu(); });</script>
    <script src="~/Assets/Client/js/simpleCart.min.js"></script>

    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    @*thông báo json*@
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/Assets/Admin/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <!--header-->
    <div class="header">
        <div class="header-top">
            <div class="container">
                @{Html.RenderAction("SearchBox", "Home"); }
                <div class="header-left">
                    <ul class="navbar-nav float-end" style="display:flex; ">
                        @if (tk != null)
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/7/7e/Circle-icons-profile.svg" class="rounded-circle" alt="avt" style="width: 35px">
                                <span><strong style="font-size: 12px;">@tk.HoTen</strong></span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end user-dd animated" aria-labelledby="navbarDropdown" style="background-color: rgb(70, 130, 180);font-size: 13px;margin-top:-9px!important;">
                                <li><a class="dropdown-item" href="@Url.Action("Index","Bill")"><i class="fas fa-shopping-basket" style=" margin-right: 10px; color: #FFFF66;"></i>Đơn hàng của bạn</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("UserInfor","AccountUser",new { id = tk.MaTK })"><i class="fas fa-user" style=" margin-right: 10px; color: #FFFF66;"></i>Thông tin tài khoản</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("ChangePassWord","AccountUser")"><i class="fas fa-lock" style=" margin-right: 10px; color: #FFFF66;"></i>Đổi mật khẩu</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Logout","Home")"><i class="fas fa-sign-out-alt" style=" margin-right: 10px; color: #FFFF66;"></i>Đăng xuất</a></li>
                            </ul>
                        </li>
}


                        @if (tk == null)
                        {
                    <li><a href="@Url.Action("Login", "Home")">Đăng nhập</a></li>
                                    <li><a href="@Url.Action("SignUp", "Home")">Đăng ký</a></li>}
                    </ul>

                    @{ Html.RenderAction("HeaderCart", "Home");}
                    <div class="clearfix"> </div>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="container">
            <div class="head-top">
                <div class="logo">
                    <a href="@Url.Action("Index","Home")"><img src="~/Assets/Client/images/logoxshop.PNG" alt=""></a>
                </div>
                <div class=" h_menu4">
                    <ul class="memenu skyblue">

                        <li><a class="color4" href="@Url.Action("Index","Home")">TRANG CHỦ</a></li>
                        <li class="grid">
                            <a class="color2" href="">DANH MỤC </a>
                            <div class="mepanel">
                                <div class="row">
                                    <div class="col">
                                        <div class="h_nav">
                                            <ul>
                                                @{ Html.RenderAction("DanhMuc", "Home");}

                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <!---->
                        <li><a class="color4" href="@Url.Action("Index","NewFeed")">BLOG</a></li>
                        <li><a class="color6" href="@Url.Action("Contact","Home")">CONTACT</a></li>
                    </ul>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>

    </div>


    <!--content-->
    <div style="margin-top:50px">
        @RenderBody()
    </div>

    <div class="footer">
        <div class="container">
            <div class="footer-top-at">



                <div class="col-md-4 amet-sed " data-aos="fade-right" data-aos-delay="200">
                    <div class="image_logo"><img src="~/Assets/Client/images/logoxshop.PNG"></div>


                    <h4>DỊCH VỤ KHÁCH HÀNG</h4>

                    <p>
                        Hướng dẫn đặt hàng
                    </p>
                    <p>Chính sách đổi trả và bảo hành</p>
                    <p>Chính sách bảo mật</p>
                    <p>Chính sách khách hàng thân thiết</p>

                </div>
                <div class="col-md-4 amet-sed" data-aos="fade-right" data-aos-delay="300">

                    <h4>THÔNG TIN</h4>
                    <p>Tuyển dụng</p>
                    <p>Hệ thống cửa hàng</p>
                    <p>Liên hệ hợp tác</p>
                    <p>Q&A</p>

                    <div class="email-box">
                        <i class="fas fa-envelope"></i>
                        <input class="tbox" type="email" name="" value="" placeholder="Enter your email">
                        <button class="btn" type="button" name="button">Subscribe</button>
                    </div>
                </div>

                <div class="col-md-4 amet-sed" data-aos="fade-right" data-aos-delay="400">
                    <h4>LIÊN HỆ</h4>
                    <ul class="nav-bottom">
                        <li><a href="#"><span>Hotline:</span>097 507 1208</a></li>
                        <li><a href="#"><span>Store 1: </span>57 Quan Hoa, Cầu Giấy, Hà Nội</a></li>
                        <li><a href="#"><span>Store 2: </span>29 Trần Đại Nghĩa, Hai Bà Trưng, Hà Nội</a></li>
                        <li><a href="#"><span>Store 3: </span>61 Trần Phú, Hà Đông, Hà Nội</a></li>
                    </ul>


                </div>
                <div class="clearfix"> </div>
            </div>
        </div>

    </div>
    @RenderSection("jsFooter", required: false)
    
    <script>
        $(document).ready(function () {
            //click to scroll top
            $('.move-up span').click(function () {
                $('html,body').animate({
                    scrollTop: 0
                }, 2000)
            })
            //Aos chuyển động của ảnh
            AOS.init();
        });
    </script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
</body>

</html>